---
# This is separate so that Ansible marks this step as changed instead of the
# next one when the packages are present
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_update_cache_valid_time | default(86400) }}"

- include: dovecot.yml
  tags: dovecot
- include: postfix.yml
  tags: postfix
- include: sql.yml
  when: sql
- include: solr.yml
  when: solr | default (False) | bool
- include: postgrey.yml
  when: postgrey
- include: sieve.yml
  when: sieve | default (False) | bool
  tags: sieve
