---
# This is separate so that Ansible marks this step as changed instead of the
# next one when the packages are present
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_update_cache_valid_time | default(86400) }}"

- include: dovecot.yml
- include: postfix.yml
- include: sql.yml
- include: postgrey.yml
