---
- name: POSTFIX | install packages
  apt:
    pkg: "{{ pkg_postfix }}"
    state: present
  notify: restart postfix

- name: POSTFIX | install ldap driver
  apt:
    pkg: postfix-ldap
    state: present
  when: ldap is defined
  notify: restart postfix

- name: POSTFIX | ensure Postfix is started and runs at startup
  service:
    name: postfix
    state: started
    enabled: yes

- name: POSTFIX | configure (main.cf)
  template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: POSTFIX | configure (master.cf)
  template:
    src: etc/postfix/master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: POSTFIX | configure (mysql-virtual-alias-maps.cf)
  template:
    src: etc/postfix/mysql-virtual-alias-maps.cf.j2
    dest: /etc/postfix/mysql-virtual-alias-maps.cf
    owner: postfix
    group: root
    mode: 0660
  when: sql | bool
  notify: restart postfix

- name: POSTFIX | configure (mysql-virtual-mailbox-domains.cf)
  template:
    src: etc/postfix/mysql-virtual-mailbox-domains.cf.j2
    dest: /etc/postfix/mysql-virtual-mailbox-domains.cf
    owner: postfix
    group: root
    mode: 0660
  when: sql | bool
  notify: restart postfix

- name: POSTFIX | configure (mysql-virtual-mailbox-maps.cf)
  template:
    src: etc/postfix/mysql-virtual-mailbox-maps.cf.j2
    dest: /etc/postfix/mysql-virtual-mailbox-maps.cf
    owner: postfix
    group: root
    mode: 0660
  when: sql | bool
  notify: restart postfix

- name: POSTFIX | configure (helo_access)
  copy:
    src: postfix_helo_access
    dest: /etc/postfix/helo_access
  notify:
  - POSTFIX | postmap /etc/postfix/helo_access (generate /etc/postfix/helo_access.db)
  - restart postfix

- name: POSTFIX | Create A Whitelist rbl (/etc/postfix/rbl_override)
  copy:
    src: postgrey-rbl_override
    dest: /etc/postfix/rbl_override
  notify:
  - POSTFIX | postmap /etc/postfix/rbl_override (generate /etc/postfix/rbl_override.db)
  - restart postfix

- name: POSTFIX | set the default domain name to be used (/etc/mailname)
  copy:
    content: "{{ postfix_default_domain }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  when: postfix_default_domain is defined

- name: POSTFIX | set relocated_maps
  copy:
    content: "{{ postfix_relocated_maps.data + '\n' }}"
    dest: "{{ postfix_relocated_maps.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  when: postfix_relocated_maps is defined

- name: POSTFIX | set aliases_maps
  copy:
    content: "{{ postfix_alias.data + '\n' }}"
    dest: "{{ postfix_alias.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  when: postfix_alias is defined

- name: POSTFIX | set postfix_local_recipient_maps
  copy:
    content: "{{ postfix_local_recipient_maps.data + '\n' }}"
    dest: "{{ postfix_local_recipient_maps.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  when: postfix_local_recipient_maps is defined
