---
- name: DOVECOT | install sieve
  apt:
    pkg:
    - dovecot-sieve
    - dovecot-managesieved
    state: present
  notify: restart dovecot

- name: DOVECOT | configure (90-sieve.conf)
  template:
    src: etc/dovecot/conf.d/90-sieve.conf.j2
    dest: /etc/dovecot/conf.d/90-sieve.conf
    owner: '{{ dovecot_user.name }}'
    group: dovecot
    mode: 0440
  notify: restart dovecot

- name: DOVECOT | configure (20-managesieve)
  template:
    src: etc/dovecot/conf.d/20-managesieve.conf.j2
    dest: /etc/dovecot/conf.d/20-managesieve.conf
    owner: '{{ dovecot_user.name }}'
    group: dovecot
    mode: 0440
  notify: restart dovecot

- name: DOVECOT | set permissions and ownership for custom sieve
  file:
    path: /etc/dovecot/sieve
    state: directory
    owner: '{{ dovecot_user.name }}'
    group: dovecot
    mode: 0755

- name: DOVECOT | Create custom sieve
  copy:
    content: "{{ item.data + '\n' }}"
    dest: "/etc/dovecot/sieve/{{ item.dest }}"
    owner: '{{ dovecot_user.name }}'
    group: dovecot
    mode: 0644
  notify: sievec
  register: sievec
  #when: custom_sieve is defined
  loop: "{{ custom_sieve | default ([]) }}"
