---
- name: SolR | install
  apt:
    pkg:
    - dovecot-solr
    - solr-tomcat
    state: present

- name: SolR | Configure schema
  template:
    src: etc/solr/conf/schema.xml.j2
    dest: /etc/solr/conf/schema.xml
    owner: 'root'
    group: root
    mode: 0444
  notify: restart tomecat

# set log level in basic way as it's can have different log level per Handlers.
# Also modify commented line ...
- name: tomcat | Definie Log level
  replace:
    dest: /etc/tomcat9/logging.properties
    backup: yes
    regexp: '^(.+level.+)\=(.+)$'
    replace: '\g<1>= {{ tomcat_loglevel | default ("FINE") }}'
  notify: restart tomecat
