---
- name: check postfix
  command: postfix check

- name: POSTFIX | postalias
  command: postalias {{ item.dest }}
  loop: "{{ postfix_virtual_alias_maps + postfix_alias_maps }}"
  when: item.type == "hash"

- name: POSTFIX | postmap
  command: postmap {{ postfix_transport_maps.dest }}

- name: POSTFIX | postmap /etc/postfix/helo_access (generate /etc/postfix/helo_access.db)
  command: postmap /etc/postfix/helo_access
  notify:
  - check postfix
  - restart postfix

- name: POSTFIX | postmap /etc/postfix/rbl_override (generate /etc/postfix/rbl_override.db)
  command: postmap /etc/postfix/rbl_override
  notify:
  - check postfix
  - restart postfix

- name: POSTFIX | postmap /etc/postfix/client_checks
  command: postmap /etc/postfix/client_checks
  notify: reload postfix

- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: restart postgrey
  service:
    name: postgrey
    state: restarted

- name: restart tomecat
  service:
    name: tomcat9
    state: restarted

- name: sievec
  command:
    cmd: "sievec {{ item.dest }}"
  become: yes
  become_user: dovecot
  loop: "{{ sievec.results }}"
